server:
  port: 8088
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server1:8081/eureka,http://eureka-server2:8082/eureka
spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:8087/
    service:
      name: ${spring.application.name}
    discovery-client-enabled: true
logging:
  level:
    zipkin2: DEBUG
debug: true
